DROP TABLE IF EXISTS TB_HEROES;
CREATE TABLE TB_HEROES(
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NOME TEXT NOT NULL,
    PODER TEXT NOT NULL
)

--CREATE
INSERT INTO TB_HEROES (NOME, PODER)
VALUES
    ('The Flash', 'Velocidade'),
    ('Aquaman', 'Falar com animais aquaticos'),
    ('Batman', 'Dinheiro');

--read
SELECT * FROM TB_HEROES;
SELECT * FROM TB_HEROES WHERE NOME = "The Flase";
SELECT * FROM TB_HEROES WHERE ID = 1;


--update
UPDATE TB_HEROES
SET NOME = 'GOKU', PODER = 'VOAR'
WHERE ID = 1;

--delete
DELETE FROM TB_HEROES WHERE ID = 2;